nya_proxy:
  host: 0.0.0.0
  port: 8080
  api_key: 
  logging:
    enabled: true
    level: debug
    log_file: nya_proxy.log
  proxy:
    enabled: false
    address: socks5://username:password@proxy.example.com:1080
  dashboard:
    enabled: true
  queue:
    enabled: true
    max_size: 200
    expiry_seconds: 110

default_settings:
  key_variable: keys
  load_balancing_strategy: round_robin
  rate_limit:
    endpoint_rate_limit: 10/s
    key_rate_limit: 10/m
  retry:
    enabled: true
    mode: key_rotation
    attempts: 3
    retry_after_seconds: 1
    retry_request_methods: [ POST, GET, PUT, DELETE, PATCH, OPTIONS ]
    retry_status_codes: [ 429, 500, 502, 503, 504 ]
  timeouts:
    request_timeout_seconds: 110
    

apis:
  gemini:
    name: Google Gemini API
    endpoint: https://generativelanguage.googleapis.com/v1beta/openai
    aliases:
    - /gemini
    key_variable: keys
    headers:
      Authorization: 'Bearer ${{keys}}'
    variables:
      keys:
      - your_gemini_key_1
      - your_gemini_key_2
      - your_gemini_key_3
    load_balancing_strategy: least_requests
    rate_limit:
      endpoint_rate_limit: 10/m
      key_rate_limit: 10/m
  openai:
    name: OpenAI API
    endpoint: https://api.openai.com
    key_variable: keys
    headers:
      Authorization: 'Bearer ${{keys}}'
    variables:
      keys:
      - your_openai_key_1
      - your_openai_key_2
    load_balancing_strategy: least_requests
    rate_limit:
      endpoint_rate_limit: 500/m
      key_rate_limit: 250/m
  test:
    name: Test API
    endpoint: http://127.0.0.1:8000
    key_variable: keys
    headers:
      Authorization: 'Bearer ${{keys}}'
      User-Agent: ${{agents}}
    variables:
      keys:
      - your_test_key_1
      - your_test_key_2
      - your_test_key_3
      agents:
      - test_agent_1
      - test_agent_2
      - test_agent_3
    load_balancing_strategy: least_requests
    rate_limit:
      endpoint_rate_limit: 20/m
      key_rate_limit: 10/m
  google:
    name: Google Search
    endpoint: https://google.com
    key_variable: agents
    headers:
      Test-Header: ${{agents}}
    variables:
      agents:
      - test_agent_1
      - test_agent_2
      - test_agent_3
    load_balancing_strategy: least_requests
    rate_limit:
      endpoint_rate_limit: 20/m
      key_rate_limit: 10/m